import{i as g,S as b}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const i of e.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function c(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function n(t){if(t.ep)return;t.ep=!0;const e=c(t);fetch(t.href,e)}})();document.querySelector(".form");const L=document.querySelector(".container"),s=document.querySelector(".form"),a=document.querySelector(".gallery");s.addEventListener("submit",S);function S(o){o.preventDefault(),$(),a.innerHTML="";const r="42059071-0978dc0d7158b742eee7c30f5",c="https://pixabay.com/api/",n=s.elements.input.value,t=`${c}?key=${r}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true,`;fetch(t).then(e=>{if(!e.ok)throw new Error(e.statusText);return e.json()}).then(e=>{if(e.hits.length===0||n==="")g.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomLeft",maxWidth:360}),s.reset();else{const i=e.hits.map(({webformatURL:u,largeImageURL:f,tags:m,likes:d,views:p,comments:h,downloads:y})=>`<a class="gallery-link "href="${f}"
          ><li>
            <img class="gallery-item "src="${u}" alt="${m}" />
            <p>Likes: ${d}</p>
            <p>Views: ${p}</p>
            <p>Comments: ${h}</p>
            <p>Downloads: ${y}</p></li
        ></a>`).join("");a.insertAdjacentHTML("beforeend",i),l.refresh(),s.reset()}}).catch(e=>{console.log(e)}).finally(()=>{q()})}function $(){const o=document.createElement("span");o.classList.add("loader"),L.append(o)}function q(){const o=document.querySelector(".loader");o&&o.remove()}const O={captions:!0,captionSelector:"img",captionsData:"alt",captionPosition:"bottom",animation:250},l=new b(".gallery a",O);l.on("show.simplelightbox");
//# sourceMappingURL=commonHelpers.js.map
